[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "percentify"
version = "0.1.0"
description = "A micro-library to easily calculate percentage between two numbers."
authors = [{ name="Daniel Emakkporuena", email="danielemakporuena1@gmail.com" }]
readme = "README.md"
license = {text = "Apache 2.0"}
requires-python = ">=3.7"
